.TH setupcondasymlink 1 "12 April 2021" "1.2.1" "setupcondasymlink man page"
.SH NAME
setupcondasymlink \- a simple script to relocate the conda cache to the work directory.

.SH SYNOPSIS
setupcondasymlink [-h] [-V] [--license]

.SH DESCRIPTION
setupcomsolsymlink is simple script that provides a high-level way for the user to relocate their conda cache to their work directory on Roar.

.SH OPTIONS
.IP "\fB-V|--version\fP"
Print setupcondasymlink version info.

.IP "\fB--license\fP"
Print setupcondasymlink licensing info.

.IP "\fB-h|--help\fP"
Print help info.

.SH FILES
.TP
.I
/gpfs/group/dml129/default/sw7/iaskutils/bin/setupcondasymlink

.TP
.I
/gpfs/group/dml129/default/sw7/iaskutils/setupcondasymlink.py

.TP
.I
/gpfs/group/dml129/default/sw7/iaskutils/utils/print_license.py

.TP
.I
/gpfs/group/dml129/default/sw7/iaskutils/utils/special_print.py

.TP
.I
/gpfs/group/dml129/default/sw7/iaskutils/utils/verifylocale.py

.SH EXAMPLES
.TP
.BI "setupcondasymlink"
.TP
.PP
Move your conda cache to your work directory and setup a symlink in your home directory on Roar.

.SH BUGS
No known bugs. If you encounter a bug using this script, please open an issue at https://github.com/ICDS-Roar/iaskutils.

.SH AUTHOR
Jason C. Nucciarone (jcn23@psu.edu, jason.nucciarone@gmail.com)

.SH COPYRIGHT
Copyright 2021 The Pennsylvania State University Institute for Computational and Data Sciences. All rights reserved at https://mit-license.org/.
